global:
  image:
    repository: my-repo/my-image
    tag: latest
  configData:
    msg: "hi how are you"
    lunch: "chicken biryani"

subchart1:
  replicaCount: 2
  image:
    tag: "1.0"
  testmsg: "i am subchart1 config value"
  configData:
    key1: value1
    key2: value2

subchart2:
  service:
    type: LoadBalancer
  configData:
    key1: value3
    key2: value4
