apiVersion: v1
kind: Service
metadata:
  name: subchart2-svc
spec:
  type: {{ .Values.service.type }}
  selector:
    app: subchart2-svc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
